version: '3.8'
services:
  mongo_db:
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    networks:
      spring-mockstock-network:
    ports:
      - 27017:27017
    volumes:
      - db:/datamongo/db

  mysqldb:
    container_name: mysqldb
    image: mysql
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    networks:
      spring-mockstock-network:
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/datasql/db

  spring-wallet-api:
    container_name: spring-wallet-api
    build:
      context: ./wallet
      dockerfile: Dockerfile
    ports:
      - $WALLET_LOCAL_PORT:$WALLET_DOCKER_PORT
    depends_on:
      - mysqldb
    networks:
      spring-mockstock-network:
    environment:
      API_KEY: $WALLET_API_KEY
      SPRING_DB_PASSWORD: $WALLET_SPRING_DB_PASSWORD
      DB_USERNAME: $WALLET_DB_USERNAME
      DB_SPRING_URL: $WALLET_SPRING_DB_URL
      DB_DOCKER_URL: $WALLET_DOCKER_DB_URL
      DOCKER_DB_PASSWORD: $WALLET_DOCKER_DB_PASSWORD
    restart: on-failure

  mock-stock-data-server:
    container_name: mock-stock-data-server
    depends_on:
      - mongo_db
      - auth-server
    build:
      context: ./apiMockStocks
      dockerfile: Dockerfile
    restart: on-failure
    env_file: ./.env
    image: mock-stock-data-server:latest
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    networks:
      - spring-mockstock-network
    environment:

      SPRING_APPLICATION_JSON: '{
          "spring.data.mongodb.uri" : "mongodb://$MONGODB_USER:$MONGODB_PASSWORD@mongo_db:$MONGODB_DOCKER_PORT/$MONGODB_DATABASE?authSource=admin"
        }'

      MONGODB_USERNAME: $MONGODB_USERNAME
      MONGODB_PASSWORD: $MONGODB_PASSWORD
      MONGODB_DATABASE: $MONGODB_DATABASE
      MONGODB_PORT: $MONGODB_PORT
      MONGODB_HOST: $MONGODB_HOST
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  auth-server:
    container_name: auth-server
    build:
      context: ./AuthorizationServerMockStock
      dockerfile: Dockerfile
    image: auth-server:latest
    ports:
      - $AUTH_LOCAL_PORT:$AUTH_DOCKER_PORT
    networks:
      - spring-mockstock-network

networks:
  spring-mockstock-network:
    driver: bridge

volumes:
  db: