name: Build, Run, and Test

on:
  push:
    branches:
      - main

jobs:
  build-run-test:
    runs-on: ubuntu-latest
    env:
      MAIL_PORT: 587
      MAIL_USERNAME: stockwalletfinance@gmail.com
      MAIL_PASSWORD: 'fakf pekt ciha eovb'


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Load environment variables
        uses: matootie/action-gh-dotenv@v2
        with:
          filename: .env
          
      - name: Run unit tests for NotificationApi
        run: |
          cd notificationApi
          mvn -B test --file pom.xml
  
      - name: Build the application
        run: |
          cd notificationApi
          mvn -B package --file pom.xml
